### ISSUE TITLE
Changing encoder keyword causes failure

### ISSUE THREAD

**Issue by rootwork** [brpaz/ulauncher-encoder#1]
Thanks for this handy extension!

From what I can tell, changing the encoder keyword to anything other than `encode` causes the new keyword to trigger decoding, not encoding. (I tried changing it to `en`, `enc`, and `encoder`.)

**Comment by brpaz** [comment]
Ulauncher doesn't have a way to identify the keyword besides it´s value. See issue: https://github.com/Ulauncher/Ulauncher/issues/284.

I need to be able to identify if it´s a decode or encode in the extension and the only way is to rely on the keyword value. So it´s not possible to change the keyword in the settings and keep this extension working.

It´s not great I know, but it´s an Ulauncher limitation.

If you really want to use a custom keyword, I would recommend forking this repo and change it here: https://github.com/brpaz/ulauncher-encoder/blob/89c96c7ae8f5965a7a5dd01a87cb7eadf34bc611/main.py#L91 

Thank you.
